config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
    get '/customers/sign_out' => 'public/sessions#destroy'
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"

  scope module: 'public' do
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    get "/customers/:id/draft" => "customers#draft", as: "draft"
    resources :customers, only: [:show, :edit, :update] do
      get :likes, on: :collection
      resource :relationships, only: [:create, :destroy]
    	get "followings" => "relationships#followings", as: "followings"
    	get "followers" => "relationships#followers", as: "followers"
    end
    resources :recipes, only: [:new, :create, :index, :show, :destroy, :update, :edit] do
      resources :comments, only: [:create, :destroy]
      resource :like, only: [:create, :destroy]
    end
    resources :genres, only: [:index]
    get '/genre/search' => 'searches#genre_search'
    get "/search", to: "searches#search"
  end

  namespace :admin do
    get "/" => "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :comments, only: [:index, :destroy]
    resources :recipes, only: [:index, :destroy]
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :recipe
  
  validates :comment, presence: true
  
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  before_action :authenticate_admin!

  def index
    @comments = Comment.all
    @customers = Customer.all
    @recipes = Recipe.all
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to admin_comments_path
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/views/admin/comments/index.html.erb
<div class="fullheight container pb-5">
  <h3 class="d-flex justify-content-center pt-5 pb-5">コメント一覧</h3>
  <table class="text table table-bordered table-hover">
    <tr class="text table-active">
      <th>名前</th>
      <th>料理名</th>
      <th>コメント</th>
      <th>投稿日</th>
      <th></th>
    </tr>

    <% @comments.each do |comment| %>
      <tr>
        <td><%= @customers.find(comment.customer_id).name %></td>
        <td><%= @recipes.find(comment.recipe_id).dish_name %></td>
        <td><%= comment.comment %></td>
        <td><%= comment.created_at.strftime('%Y/%m/%d') %></td>
        <td>
          <%= link_to "削除", admin_comment_path(comment), method: :delete, data: { confirm: '本当に削除しますか？' },class: "btn btn-danger" %>
        </td>
      </tr>
    <% end %>
  </table>
</div>