config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
    get '/customers/sign_out' => 'public/sessions#destroy'
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"

  scope module: 'public' do
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    get "/customers/:id/draft" => "customers#draft", as: "draft"
    resources :customers, only: [:show, :edit, :update] do
      get :likes, on: :collection
      resource :relationships, only: [:create, :destroy]
    	get "followings" => "relationships#followings", as: "followings"
    	get "followers" => "relationships#followers", as: "followers"
    end
    resources :recipes, only: [:new, :create, :index, :show, :destroy, :update, :edit] do
      resources :comments, only: [:create, :destroy]
      resource :like, only: [:create, :destroy]
    end
    resources :genres, only: [:index]
    get '/genre/search' => 'searches#genre_search'
    get "/search", to: "searches#search"
  end

  namespace :admin do
    get "/" => "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :comments, only: [:index, :destroy]
    resources :recipes, only: [:index, :destroy]
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :customer
  belongs_to :genre, optional: true
  has_many :recipe_details, dependent: :destroy
  accepts_nested_attributes_for :recipe_details, reject_if: :all_blank, allow_destroy: true
  has_many :recipe_steps, dependent: :destroy
  accepts_nested_attributes_for :recipe_steps, reject_if: :all_blank, allow_destroy: true
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  enum status: { published: 0, draft: 1, unpublished: 2 }

  def self.search_for(content, method)
    if method == 'perfect'
      Recipe.where(dish_name: content)
    elsif method == 'forward'
      Recipe.where('dish_name LIKE ?', content + '%')
    elsif method == 'backward'
      Recipe.where('dish_name LIKE ?', '%' + content)
    else
      Recipe.where('dish_name LIKE ?', '%' + content + '%')
    end
  end

  def liked_by?(customer)
    likes.exists?(customer_id: customer.id)
  end

  scope :latest, -> {order(created_at: :desc)}

  with_options if: :published? do
    validates :image, presence: true
    validates :dish_name, presence: true
    validates :explanation, presence: true
    validates :difficulty, presence: true
    validates :cooking_time, presence: true
    validates :genre_id, presence: true
    
     validates_associated :recipe_details
  validates :recipe_details, presence: true
  
  validates_associated :recipe_steps
  validates :recipe_steps, presence: true
  end
end

app/controllers/admin/recipes_controller.rb
class Admin::RecipesController < ApplicationController
  before_action :authenticate_admin!

  def index
    @recipes = Recipe.published.order(created_at: :desc).page(params[:page]).per(10)
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to admin_recipes_path
  end
end

app/helpers/admin/recipes_helper.rb
module Admin::RecipesHelper
end

app/views/admin/recipes/index.html.erb
<div class="container">
  <h3 class="text-title d-flex justify-content-center pt-5 -b-5">レシピ一覧</h3>
  <div class="row">
    <%= link_to "コメント一覧へ", admin_comments_path, class: "text btn btn-outline-secondary mb-3 mr-5 ml-auto" %>
  </div>
  <div class="row">
    <div class="col-2"></div>
    <table class="table table-hover table-inverse col-9">
      <tr class="table-active">
        <th class="text col-1">レシピID</th>
        <th class="text col-2">投稿日</th>
        <th class="text col-2">レシピ名</th>
        <th class="text col-2">ユーザ名</th>
        <th class="text col-2"></th>
      </tr>
      <% @recipes.each do |recipe| %>
        <tr>
          <td class="text">
            <%= recipe.id %>
          </td>
          <td class="text">
            <%= recipe.created_at.strftime('%Y/%m/%d') %>
          </td>
          <td class="text">
            <%= recipe.dish_name %>
          </td>
          <td class="text">
           <%= recipe.customer.name %>
          </td>
          <td>
            <%= link_to "削除する", admin_recipe_path(recipe.id), method: :delete, "data-confirm" => "投稿を削除しますか？", class: "btn btn-danger"%>
          </td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="d-flex justify-content-center mb-4">
    <%= paginate(@recipes) %>
  </div>
</div>