config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
    get '/customers/sign_out' => 'public/sessions#destroy'
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"

  scope module: 'public' do
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    get "/customers/:id/draft" => "customers#draft", as: "draft"
    resources :customers, only: [:show, :edit, :update] do
      get :likes, on: :collection
      resource :relationships, only: [:create, :destroy]
    	get "followings" => "relationships#followings", as: "followings"
    	get "followers" => "relationships#followers", as: "followers"
    end
    resources :recipes, only: [:new, :create, :index, :show, :destroy, :update, :edit] do
      resources :comments, only: [:create, :destroy]
      resource :like, only: [:create, :destroy]
    end
    resources :genres, only: [:index]
    get '/genre/search' => 'searches#genre_search'
    get "/search", to: "searches#search"
  end

  namespace :admin do
    get "/" => "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :comments, only: [:index, :destroy]
    resources :recipes, only: [:index, :destroy]
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id",dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_one_attached :image
  validate

  def follow(customer)
    active_relationships.create(followed_id: customer.id)
  end

  def unfollow(customer)
    active_relationships.find_by(followed_id: customer.id).destroy
  end

  def following?(customer)
    followings.include?(customer)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "ゲスト"
    end
  end



  scope :latest, -> {order(created_at: :desc)}
    validates :image, presence: true, on: :publish
    validates :dish_name, presence: true, on: :publish
    validates :explanation, presence: true, on: :publish
    validates :difficulty, presence: true, on: :publish
    validates :cooking_time, presence: true, on: :publish
    validates :genre_id, presence: true, on: :publish
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page]).per(10)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    @customer.update(customer_params)
    redirect_to admin_customer_path(@customer.id)
  end
  
  def customer_params
    params.require(:customer).permit(:id, :name, :email, :is_active)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="fullheight container">
  <h3 class="text-title d-flex justify-content-center pt-4 pb-4"><%= @customer.name %>さんの会員情報編集</h3>
  <%= form_with model: [:admin,@customer] do |f| %>
      <div class="row">
        <div class="col-4"></div>
        <div class="text col-2 mb-3">
          <%= f.label :"会員ID" %>
        </div>
        <div class="text mb-3">
          <%= @customer.id %>
        </div>
      </div>
  
      <div class="row">
        <div class="col-4"></div>
        <div class="text col-2 mb-3">
          <%= f.label :"ユーザ名" %>
        </div>
        <div class="mb-3">
          <%= f.text_field :name %>
        </div>
      </div>
  
      <div class="row">
        <div class="col-4"></div>
        <div class="text col-2 mb-3">
          <%= f.label :"メールアドレス" %>
        </div>
        <div class="mb-3">
          <%= f.text_field :email %>
        </div>
      </div>
  
      <div class="row">
        <div class="col-4"></div>
        <div class="text col-2 mb-3">
          <%= f.label :"会員ステータス" %>
        </div>
        <div class="text mb-3">
          <%= f.radio_button :is_active, "true" %>
          <%= f.label :is_active_valid, "有効", :class => "mr-5" %>
          <%= f.radio_button :is_active, "false" %>
          <%= f.label :is_active_sale_Withdrawal, "退会" %>
        </div>
      </div>
  
      <div class="d-flex justify-content-center">
        <%= f.submit '変更を保存', class: "btn btn-success" %>
      </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <h2 class="text-title d-flex justify-content-center pt-5">会員一覧</h2>
  <table class="table table-hover table-inverse">
    <tr class="table-active">
      <th class="col-1">会員ID</th>
      <th class="col-2">ユーザ名</th>
      <th class="col-2">メールアドレス</th>
      <th class="col-2">ステータス</th>
    </tr>
    <% @customers.each do |customer| %>
      <tr>
        <td class="text">
          <%= customer.id %>
        </td>
        <td>
          <%= link_to customer.name, admin_customer_path(customer.id),class: "text" %>
        </td>
        <td class="text">
          <%= customer.email %>
        </td>
        <td>
          <% if customer.is_active %>
            <p class="text-success"><strong>有効</strong></p>
          <% elsif %>
            <p class="text-muted"><strong>退会</strong></p>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <div class="d-flex justify-content-center">
    <%= paginate(@customers) %>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="fullheight container">
  <h3 class="text-title d-flex justify-content-center pt-4 pb-4"><%= @customer.name %>さんの詳細ページ</h3>

  <div class="row">
    <div class="col-4"></div>
    <div class="text col-2 mb-4">会員ID</div>
    <div class="text"><%= @customer.id %></div>
  </div>

  <div class="row">
    <div class="col-4"></div>
    <div class="text col-2 mb-4">ユーザ名</div>
    <div class="text"><%= @customer.name %></div>
  </div>

  <div class="row">
    <div class="col-4"></div>
    <div class="text col-2 mb-4">メールアドレス</div>
    <div class="text"><%= @customer.email %></div>
  </div>
  <div class="row">
    <div class="col-4"></div>
    <div class="text col-2 mb-4">会員ステータス</div>
    <% if @customer.is_active %>
      <p class="text-success"><strong>有効</strong></p>
    <% elsif %>
      <p class="text-muted"><strong>退会</strong></p>
    <% end %>
  </div>
  <div class="d-flex justify-content-center">
    <%= link_to "編集する", edit_admin_customer_path(@customer.id), class: "btn btn-success mr-5" %>
  </div>
</div>