config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_scope :customer do
    post 'customers/guest_sign_in', to: 'public/sessions#guest_sign_in'
    get '/customers/sign_out' => 'public/sessions#destroy'
  end

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"

  scope module: 'public' do
    get "customers/unsubscribe" => "customers#unsubscribe"
    patch "customers/withdraw" => "customers#withdraw"
    get "/customers/:id/draft" => "customers#draft", as: "draft"
    resources :customers, only: [:show, :edit, :update] do
      get :likes, on: :collection
      resource :relationships, only: [:create, :destroy]
    	get "followings" => "relationships#followings", as: "followings"
    	get "followers" => "relationships#followers", as: "followers"
    end
    resources :recipes, only: [:new, :create, :index, :show, :destroy, :update, :edit] do
      resources :comments, only: [:create, :destroy]
      resource :like, only: [:create, :destroy]
    end
    resources :genres, only: [:index]
    get '/genre/search' => 'searches#genre_search'
    get "/search", to: "searches#search"
  end

  namespace :admin do
    get "/" => "homes#top"
    resources :genres, only: [:index, :create, :edit, :update]
    resources :customers, only: [:index, :show, :edit, :update]
    resources :comments, only: [:index, :destroy]
    resources :recipes, only: [:index, :destroy]
  end



  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :customer
  belongs_to :recipe
  
  validates :comment, presence: true
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true
  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id",dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  has_one_attached :image
  validate

  def follow(customer)
    active_relationships.create(followed_id: customer.id)
  end

  def unfollow(customer)
    active_relationships.find_by(followed_id: customer.id).destroy
  end

  def following?(customer)
    followings.include?(customer)
  end

  def self.guest
    find_or_create_by!(email: 'guest@example.com') do |customer|
      customer.password = SecureRandom.urlsafe_base64
      customer.name = "ゲスト"
    end
  end



  scope :latest, -> {order(created_at: :desc)}
    validates :image, presence: true, on: :publish
    validates :dish_name, presence: true, on: :publish
    validates :explanation, presence: true, on: :publish
    validates :difficulty, presence: true, on: :publish
    validates :cooking_time, presence: true, on: :publish
    validates :genre_id, presence: true, on: :publish
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :recipes, dependent: :destroy
  
  enum payment_method: { credit_card: 0, transfer: 1 }
end

app/models/home.rb
class Home < ApplicationRecord
  scope :latest, -> {order(created_at: :desc)}
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :customer
  belongs_to :recipe
  
  validates :customer_id, uniqueness: {scope: :recipe_id}
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :customer
  belongs_to :genre, optional: true
  has_many :recipe_details, dependent: :destroy
  accepts_nested_attributes_for :recipe_details, reject_if: :all_blank, allow_destroy: true
  has_many :recipe_steps, dependent: :destroy
  accepts_nested_attributes_for :recipe_steps, reject_if: :all_blank, allow_destroy: true
  has_one_attached :image
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  enum status: { published: 0, draft: 1, unpublished: 2 }

  def self.search_for(content, method)
    if method == 'perfect'
      Recipe.where(dish_name: content)
    elsif method == 'forward'
      Recipe.where('dish_name LIKE ?', content + '%')
    elsif method == 'backward'
      Recipe.where('dish_name LIKE ?', '%' + content)
    else
      Recipe.where('dish_name LIKE ?', '%' + content + '%')
    end
  end

  def liked_by?(customer)
    likes.exists?(customer_id: customer.id)
  end

  scope :latest, -> {order(created_at: :desc)}

  with_options if: :published? do
    validates :image, presence: true
    validates :dish_name, presence: true
    validates :explanation, presence: true
    validates :difficulty, presence: true
    validates :cooking_time, presence: true
    validates :genre_id, presence: true
    
     validates_associated :recipe_details
  validates :recipe_details, presence: true
  
  validates_associated :recipe_steps
  validates :recipe_steps, presence: true
  end
end

app/models/recipe_detail.rb
class RecipeDetail < ApplicationRecord
  belongs_to :recipe
  
  validates :ingredient, presence: true
  validates :quantity, presence: true
end

app/models/recipe_step.rb
class RecipeStep < ApplicationRecord
  belongs_to :recipe
  has_one_attached :image
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "Customer"
  belongs_to :followed, class_name: "Customer"
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
  private
  
  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/recipes_helper.rb
module Admin::RecipesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger" role="alert">
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> 保存されていません</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="html">
  <head>
    <title>CampmeshiClub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body class="body min-vh-100 d-flex flex-column">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container-fluid">
          <div>
            <%= link_to root_path do %>
              <%= image_tag 'logo.png', size: '70x70' %>
            <% end %>
            <span class="header-title h4">キャンプ飯倶楽部</span>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <div class="d-flex">
              <ul class="navbar-nav ml-auto">
                <% if customer_signed_in? %>
                  <li class="nav-item mr-lg-5">
                    <%= link_to "マイページ", current_customer,class: 'nav-link p-0 text-center',data: {"turbolinks"=>false} %>
                  </li>
                  <li class="nav-item mr-lg-5">
                    <%= link_to "レシピ一覧", recipes_path,class: 'nav-link p-0 text-center',data: {"turbolinks"=>false} %>
                  </li>
                  <li class="nav-item mr-lg-5">
                    <%= link_to "新規投稿", new_recipe_path,class: 'nav-link p-0 text-center',data: {"turbolinks"=>false} %>
                  </li>
                  <li class="nav-item mr-lg-5">
                    <%= link_to "ログアウト", destroy_customer_session_path,class: 'nav-link p-0 text-center', method: :delete %>
                  </li>
                <% elsif admin_signed_in? %>
                  <li class="nav-item mr-lg-5">
                    <%= link_to "会員一覧", admin_customers_path,class: 'nav-link p-0 text-center',data: {"turbolinks"=>false} %>
                  </li>
                  <li class="nav-item mr-lg-5">
                    <%= link_to "レシピ一覧", admin_recipes_path,class: 'nav-link p-0 text-center',data: {"turbolinks"=>false} %>
                  </li>
                  <li class="nav-item mr-lg-5">
                    <%= link_to "ジャンル一覧", admin_genres_path,class: 'nav-link p-0 text-center',data: {"turbolinks"=>false} %>
                  </li>
                  <li class="nav-item mr-lg-5">
                    <%= link_to "ログアウト", destroy_admin_session_path,class: 'nav-link p-0 text-center', method: :delete %>
                  </li>
                <% else %>
                  <li class="nav-item mr-lg-5">
                    <%= link_to 'ゲストログイン', customers_guest_sign_in_path, class: "nav-link p-0 text-center", method: :post,data: {"turbolinks"=>false} %>
                  </li>
                  <li class="nav-item mr-lg-5">
                    <%= link_to "レシピ一覧", recipes_path,class: 'nav-link p-0 text-center',data: {"turbolinks"=>false} %>
                  </li>
                  <li class="nav-item mr-lg-5">
                    <%= link_to "ログイン", new_customer_session_path,class: 'nav-link p-0 text-center',data: {"turbolinks"=>false} %>
                  </li>
                  <li class="nav-item mr-lg-5">
                    <%= link_to "新規登録", new_customer_registration_path,class: 'nav-link p-0 text-center',data: {"turbolinks"=>false}%>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
        <div class="ml-auto">
        　　<%= render "/public/searches/form" %>
        </div>
      </nav>
    </header>
    <main class="main flex-grow-1">
      <script src="https://kit.fontawesome.com/9c11671e7c.js" crossorigin="anonymous"></script>
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </main>
    <footer class="footer d-flex align-items-center justify-content-center">
      <div class="container-fluid">
        <div class="d-flex align-items-center justify-content-center">
          <%= link_to root_path do %>
            <%= image_tag 'logo.png', size: '40x40' %>
          <% end %>
          <span class="footer-title">キャンプ飯倶楽部</span>
        </div>
      </div>
    </footer>

  </body>
</html>